-- -*- mode:sql sql-product:sqlite -*-

PRAGMA foreign_keys = ON; -- database requires foreign key checking to be turned
                          -- on PER CONNECTION

-- TODO Insert descriptions from pgs 283-84

BEGIN TRANSACTION;
INSERT INTO weapongroups VALUES(1,1,'283','Axe','TODO descr from pg 283-84');
INSERT INTO weapongroups VALUES(2,1,'284','Bomb','TODO descr from pg 283-84');
INSERT INTO weapongroups VALUES(3,1,'284','Bow','TODO descr from pg 283-84');
INSERT INTO weapongroups VALUES(4,1,'284','Brawling','TODO descr from pg 283-84');
INSERT INTO weapongroups VALUES(5,1,'284','Club','TODO descr from pg 283-84');
INSERT INTO weapongroups VALUES(6,1,'284','Dart','TODO descr from pg 283-84');
INSERT INTO weapongroups VALUES(7,1,'284','Flail','TODO descr from pg 283-84');
INSERT INTO weapongroups VALUES(8,1,'284','Hammer','TODO descr from pg 283-84');
INSERT INTO weapongroups VALUES(9,1,'284','Knife','TODO descr from pg 283-84');
INSERT INTO weapongroups VALUES(10,1,'284','Pick','TODO descr from pg 283-84');
INSERT INTO weapongroups VALUES(11,1,'284','Polearm','TODO descr from pg 283-84');
INSERT INTO weapongroups VALUES(12,1,'284','Shield','TODO descr from pg 283-84');
INSERT INTO weapongroups VALUES(13,1,'284','Sling','TODO descr from pg 283-84');
INSERT INTO weapongroups VALUES(14,1,'284','Spear','TODO descr from pg 283-84');
INSERT INTO weapongroups VALUES(15,1,'284','Sword','TODO descr from pg 283-84');
COMMIT;

BEGIN TRANSACTION;
INSERT INTO weaponcategories VALUES(1, 'Unarmed');
INSERT INTO weaponcategories VALUES(2, 'Simple');
INSERT INTO weaponcategories VALUES(3, 'Martial');
INSERT INTO weaponcategories VALUES(4, 'Advanced');
COMMIT;

BEGIN TRANSACTION;
INSERT INTO weapons VALUES(0,1,'280',1,4,'0',4,1,'0','1',NULL,NULL,'Fist','Nethys Note: no description was provided for this item');
INSERT INTO weapons VALUES(1,1,'280',2,9,'2',4,2,'0.1','1',NULL,NULL,'Clan Dagger','This broad dagger is carried by dwarves as a weapon, tool, and designation of clan. Losing or having to surrender a clan dagger is considered a mark of embarrassment to most dwarves.');
INSERT INTO weapons VALUES(2,1,'280',2,5,'0',6,1,'1','1',NULL,NULL,'Club','This is a piece of stout wood shaped or repurposed to bludgeon an enemy. Clubs can be intricately carved pieces of martial art or as simple as a tree branch or piece of wood.');
INSERT INTO weapons VALUES(3,1,'280',2,9,'0.2',4,2,'0.1','1',NULL,NULL,'Dagger','This small, bladed weapon is held in one hand and used to stab a creature in close combat. It can also be thrown.');
INSERT INTO weapons VALUES(4,1,'280',2,4,'0.2',4,1,'0.1','1',NULL,NULL,'Gauntlet','A pair of these metal gloves comes with full plate, half plate, and splint armor; they can also be purchased separately and worn with other types of armor. They not only protect your hands but also transform your hands into lethal weapons.');
INSERT INTO weapons VALUES(5,1,'280',2,9,'0.3',4,2,'0.1','1',NULL,NULL,'Katar','Also known as punching daggers, katars are characterized by their H-shaped hand grip that allows the blade to jut out from the knuckles.');
INSERT INTO weapons VALUES(6,1,'280',2,5,'0.4',4,1,'0.1','1',NULL,NULL,'Light Mace','A light mace has a short wooden or metal shaft ending with a dense metal head. Used much like a club, it delivers heavy bludgeoning blows, but with extra power derived from the head’s metal ridges or spikes.');
INSERT INTO weapons VALUES(7,1,'280',2,14,'0.5',8,2,'2','2',NULL,NULL,'Longspear','This very long spear, sometimes called a pike, is purely for thrusting rather than throwing. Used by many soldiers and city watch for crowd control and defense against charging enemies, it must be wielded with two hands.');
INSERT INTO weapons VALUES(8,1,'280',2,5,'1',6,1,'1','1',NULL,NULL,'Mace','With a stout haft and a heavy metal head, a mace is sturdy and allows its wielder to deliver powerful blows and dent armor.');
INSERT INTO weapons VALUES(9,1,'280',2,5,'1',6,1,'1','1',NULL,NULL,'Morningstar','This weapon has a short shaft ending in a metal ball studded with spikes.');
INSERT INTO weapons VALUES(10,1,'280',2,9,'0.2',4,3,'0.1','1',NULL,NULL,'Sickle','Originally a farming tool used for reaping grain, this one-handed weapon has a short wooden handle ending in a curved blade, sometimes sharpened on both sides.');
INSERT INTO weapons VALUES(11,1,'280',2,14,'0.1',6,2,'1','1',NULL,NULL,'Spear','A long metal shaft ending with a metal spike, a spear can be used one-handed as a melee weapon and can be thrown.');
INSERT INTO weapons VALUES(12,1,'280',2,4,'0.3',4,2,'0.1','1',NULL,NULL,'Spiked Gauntlet','Providing the same defensive function as a standard gauntlet, this version has a group of spikes protruding from the knuckles to deliver piercing damage with a punch.');
INSERT INTO weapons VALUES(13,1,'280',2,5,'0',4,1,'1','1',NULL,NULL,'Staff','This long piece of wood can aid in walking and deliver a mighty blow.');
INSERT INTO weapons VALUES(14,1,'280',3,15,'4',8,3,'1','1',NULL,NULL,'Bastard Sword','This broad-bladed sword, sometimes called the hand‑and‑a‑half sword, has a longer grip so it can be held in one hand or used with two hands to provide extra piercing or slashing power.');
INSERT INTO weapons VALUES(15,1,'280',3,1,'0.1',8,3,'1','1',NULL,NULL,'Battle Axe','These axes are designed explicitly as weapons, rather than tools. They typically weigh less, with a shaft reinforced with metal bands or bolts, and have a sharper blade, making them ideal for chopping limbs rather than wood.');
INSERT INTO weapons VALUES(16,1,'280',3,5,'0.2',8,1,'2','2',NULL,NULL,'Bo Staff','This strong but slender staff is tapered at the ends and well balanced. It’s designed to be an offensive and defensive weapon.');
INSERT INTO weapons VALUES(17,1,'280',3,15,'0.1',6,3,'0.1','1',NULL,NULL,'Dogslicer','This short, curved, and crude makeshift blade often has holes drilled into it to reduce its weight. It’s a favored weapon of goblins.');
INSERT INTO weapons VALUES(18,1,'281',3,15,'4',8,3,'2','2',NULL,NULL,'Elven Curve Blade','Essentially a longer version of the scimitar, this traditional elven weapon has a thinner blade than its cousin.');
INSERT INTO weapons VALUES(19,1,'280',3,15,'3',10,3,'2','2',NULL,NULL,'Falchion','This weapon is a heavier, two-handed version of the curved-bladed scimitar. It is weighted toward the blade’s end, making it a powerful slashing weapon.');
INSERT INTO weapons VALUES(20,1,'281',3,14,'1',4,2,'0.1','1',NULL,NULL,'Filcher''s Fork','This halfling weapon looks like a long, two-pronged fork and is used as both a weapon and a cooking implement.');
INSERT INTO weapons VALUES(21,1,'280',3,7,'1',6,1,'1','1',NULL,NULL,'Flail','This weapon consists of a wooden handle attached to a spiked ball or cylinder by a chain, rope, or strap of leather.');
INSERT INTO weapons VALUES(22,1,'280',3,11,'2',8,3,'2','2',NULL,NULL,'Glaive','This polearm consists of a long, single-edged blade on the end of a 7-foot pole. It is extremely effective at delivering lethal cuts at a distance.');
INSERT INTO weapons VALUES(23,1,'281',3,8,'2',6,1,'1','1',NULL,NULL,'Gnome Hooked Hammer','This gnome tool and weapon features a hammer at one end and a curved pick on the other. It’s such a strange and awkward weapon that others think the gnomes are slightly erratic for using it.');
INSERT INTO weapons VALUES(24,1,'280',3,1,'1',12,3,'2','2',NULL,NULL,'Greataxe','This large battle axe is too heavy to wield with only one hand. Many greataxes incorporate two blades, and they are often “bearded,” having a hook at the bottom to increase the strength of their chopping power.');
INSERT INTO weapons VALUES(25,1,'280',3,5,'1',10,1,'2','2',NULL,NULL,'Greatclub','While many greatclubs are intricately carved, others are little more than a sturdy tree branch. These massive clubs are too heavy to wield with only one hand.');
INSERT INTO weapons VALUES(26,1,'280',3,10,'2',10,2,'2','2',NULL,NULL,'Greatpick','This pick has a longer handle and broader head than a regular pick. It is too heavy to wield in one hand.');
INSERT INTO weapons VALUES(27,1,'280',3,15,'2',12,3,'2','2',NULL,NULL,'Greatsword','This immense two-handed sword is nearly as tall as its wielder. Its lower blade is often somewhat dulled to allow it to be gripped for extra leverage in close-quarter fights.');
INSERT INTO weapons VALUES(28,1,'280',3,11,'2',10,3,'2','2',NULL,NULL,'Guisarme','This polearm bears a long, often one‑sided, curved blade with a hook protruding from the blunt side of the blade, which can allow its wielder to trip opponents at a distance. Its shaft is usually 8 feet long.');
INSERT INTO weapons VALUES(29,1,'280',3,11,'2',10,2,'2','2',NULL,NULL,'Halberd','This polearm has a relatively short, 5-foot shaft. The business end is a long spike with an axe blade attached.');
INSERT INTO weapons VALUES(30,1,'280',3,1,'0.4',6,3,'0.1','1',NULL,NULL,'Hatchet','This small axe can be used in close combat or thrown.');
INSERT INTO weapons VALUES(31,1,'281',3,11,'0.9',8,3,'2','2',NULL,NULL,'Horsechopper','Created by goblins to battle horses, this weapon is essentially a long shaft ending in a blade with a large hook.');
INSERT INTO weapons VALUES(32,1,'281',3,9,'1',6,3,'0.1','1',NULL,NULL,'Kama','Similar to a sickle and used in some regions to reap grain, a kama has a short, slightly curved blade and a wooden handle.');
INSERT INTO weapons VALUES(33,1,'281',3,15,'2',6,3,'1','1',NULL,NULL,'Katana','A katana is a curved, single-edged sword known for its wickedly sharped blade.');
INSERT INTO weapons VALUES(34,1,'281',3,9,'0.6',6,3,'0.1','1',NULL,NULL,'Kukri','The blade of this foot-long knife curves inward and lacks a cross guard at the hilt.');
INSERT INTO weapons VALUES(35,1,'280',3,14,'1',8,2,'2','2',NULL,NULL,'Lance','This spear-like weapon is used by a mounted creature to deal a great deal of damage.');
INSERT INTO weapons VALUES(36,1,'281',3,8,'0.3',6,1,'0.1','1',NULL,NULL,'Light Hammer','This smaller version of the warhammer has a wooden or metal shaft ending in a metal head. Unlike its heavier cousin, it is light enough to throw.');
INSERT INTO weapons VALUES(37,1,'281',3,10,'0.4',4,2,'0.1','1',NULL,NULL,'Light Pick','A light pick is a modified mining implement with a wooden shaft ending in a pick head crafted more to pierce armor and flesh than chip rocks.');
INSERT INTO weapons VALUES(38,1,'281',3,15,'1',8,3,'1','1',NULL,NULL,'Longsword','Longswords can be one-edged or two‑edged swords. Their blades are heavy and they’re between 3 and 4 feet in length.');
INSERT INTO weapons VALUES(39,1,'281',3,9,'0.5',4,2,'0.1','1',NULL,NULL,'Main-gauche','This parrying dagger features a robust guard to protect the wielder’s hand.');
INSERT INTO weapons VALUES(40,1,'281',3,8,'3',12,1,'2','2',NULL,NULL,'Maul','Mauls are massive warhammers that must be swung with two hands.');
INSERT INTO weapons VALUES(41,1,'281',3,5,'0.2',6,1,'0.1','1',NULL,NULL,'Nunchaku','The nunchaku is constructed of two wooden or metal bars connected by a short length of rope or chain.');
INSERT INTO weapons VALUES(42,1,'281',3,9,'0.7',6,2,'0.1','1',NULL,NULL,'Orc Knuckle Dagger','This stout, metal blade of orc design has a horizontal basket hilt with blades jutting from each end, or sometimes one blade like that of a katar.');
INSERT INTO weapons VALUES(43,1,'281',3,10,'0.7',6,2,'1','1',NULL,NULL,'Pick','A pick designed solely for combat has a sturdy wooden shaft and a heavy, pointed head to deliver devastating blows.');
INSERT INTO weapons VALUES(44,1,'281',3,11,'2',10,2,'2','2',NULL,NULL,'Ranseur','This polearm is a long trident with a central prong that’s longer than the other two.');
INSERT INTO weapons VALUES(45,1,'281',3,15,'2',6,2,'1','1',NULL,NULL,'Rapier','The rapier is a long and thin piercing blade with a basket hilt. It is prized among many as a dueling weapon.');
INSERT INTO weapons VALUES(46,1,'281',3,9,'0.6',4,2,'0.1','1',NULL,NULL,'Sai','This piercing dagger is a metal spike flanked by a pair of prongs that can be used to trap an enemy’s weapon.');
INSERT INTO weapons VALUES(47,1,'281',3,5,'0.1',6,1,'0.1','1',NULL,NULL,'Sap','A sap has a soft wrapping around a dense core, typically a leather sheath around a lead rod. Its head is wider than its grip to disperse the force of a blow, as the weapon’s purpose is to knock out its victim rather than to draw blood.');
INSERT INTO weapons VALUES(48,1,'281',3,15,'1',6,3,'1','1',NULL,NULL,'Scimitar','This one-handed curved blade is sharp on one side.');
INSERT INTO weapons VALUES(49,1,'281',3,11,'2',10,3,'2','2',NULL,NULL,'Scythe','Derived from a farming tool used to mow down long grains and cereals, this weapon has a long wooden shaft with protruding handles, capped with a curved blade set at a right angle.');
INSERT INTO weapons VALUES(50,1,'281',3,12,'0',4,1,'0','1',NULL,NULL,'Shield Bash','A shield bash is not actually a weapon, but a maneuver in which you thrust or swing your shield to hit your foe with an impromptu attack.');
INSERT INTO weapons VALUES(51,1,'281',3,12,'0.5',6,1,'0','1',NULL,NULL,'Shield Boss','Typically a round, convex, or conical piece of thick metal attached to the center of a shield, a shield boss increases the bludgeoning damage of a shield bash.');
INSERT INTO weapons VALUES(52,1,'281',3,12,'0.5',6,2,'0','1',NULL,NULL,'Shield Spikes','These metal spikes are strategically placed on the defensive side of the shield to deal piercing damage with a shield bash.');
INSERT INTO weapons VALUES(53,1,'281',3,15,'0.9',6,2,'0.1','1',NULL,NULL,'Shortsword','These blades come in a variety of shapes and styles, but they are typically 2 feet long.');
INSERT INTO weapons VALUES(54,1,'281',3,7,'3',8,3,'1','2',NULL,NULL,'Spiked Chain','This 4‑foot‑long length of chain is covered with barbs and has spikes on one or both ends. Some feature metal hoops used as handgrips.');
INSERT INTO weapons VALUES(55,1,'281',3,9,'2',4,2,'0.1','1',NULL,NULL,'Starknife','From a central metal ring, four tapering metal blades extend like points on a compass rose. When gripping a starknife from the center, the wielder can use it as a melee weapon. It can also be thrown short distances.');
INSERT INTO weapons VALUES(56,1,'281',3,15,'2',8,3,'1','1',NULL,NULL,'Temple Sword','This heavy blade is favored by guardians of religious sites. It has a distinctive, crescent-shaped blade that seems to be a mix of a sickle and sword. It often has holes drilled into the blade or the pommel so that bells or other holy trinkets can be affixed to the weapon as an aid for prayer or mediation.');
INSERT INTO weapons VALUES(57,1,'281',3,14,'1',8,2,'1','1',NULL,NULL,'Trident','This three-pronged, spear-like weapon typically has a 4-foot shaft. Like a spear, it can be wielded with one hand or thrown.');
INSERT INTO weapons VALUES(58,1,'281',3,7,'2',10,1,'2','2',NULL,NULL,'War Flail','');
INSERT INTO weapons VALUES(59,1,'281',3,8,'1',8,1,'1','1',NULL,NULL,'Warhammer','This weapon has a wooden shaft ending in a large, heavy metal head. The head of the hammer might be single-sided or double-sided, but it’s always capable of delivering powerful bludgeoning blows.');
INSERT INTO weapons VALUES(60,1,'281',3,7,'0.1',4,3,'1','1',NULL,NULL,'Whip','This long strand of thick leather, often braided, delivers a painful but nonlethal slash at a distance, usually accompanied by a distinctive cracking sound.');
INSERT INTO weapons VALUES(61,2,'85',4,5,'5',6,1,'1','1',NULL,NULL,'Aklys','');
INSERT INTO weapons VALUES(62,1,'281',4,1,'3',8,3,'2','1',NULL,NULL,'Dwarven War Axe','This favored weapon of the dwarves has a large, ornate head mounted on a thick handle. This powerful axe can be wielded with one hand or two.');
INSERT INTO weapons VALUES(63,1,'281',4,7,'3',8,1,'2','1',NULL,NULL,'Gnome Flickmace','More a flail than a mace, this weapon has a short handle attached to a length of chain with a ball at the end. The ball is propelled to its reach with the flick of the wrist, the momentum of which brings the ball back to the wielder after the strike.');
INSERT INTO weapons VALUES(64,1,'281',4,1,'2',8,3,'1','1',NULL,NULL,'Orc Necksplitter','This single-bladed bearded axe has a jagged blade that’s perfect for separating bone from tendon and cartilage.');
INSERT INTO weapons VALUES(65,1,'281',4,15,'5',8,3,'0.1','1',NULL,NULL,'Sawtooth Saber','The signature weapon of the Red Mantis assassins, this curved blade is serrated like a saw, hence the name.');
INSERT INTO weapons VALUES(66,2,'253',4,10,'1',10,2,'2','2',NULL,NULL,'Ogre Hook','Ogres are known for using immense, curved picks called ogre hooks.');
INSERT INTO weapons VALUES(67,1,'281',2,6,'0.1',1,2,'0.1','1',20,'1','Blowgun','This long, narrow tube is used for shooting blowgun darts, using only the power of a forcefully exhaled breath.');
INSERT INTO weapons VALUES(68,1,'281',2,3,'3',8,2,'1','2',120,'1','Crossbow','This ranged weapon has a bow-like assembly mounted on a handled frame called a tiller. The tiller has a mechanism to lock the bowstring in place, attached to a trigger mechanism that releases the tension and launches a bolt.');
INSERT INTO weapons VALUES(69,1,'281',2,6,'0.01',4,2,'0.1','1',20,'','Dart','This thrown weapon is larger than an arrow but shorter than a javelin. It typically has a short shaft of wood ending in a metal tip and is sometimes stabilized by feathers or fur.');
INSERT INTO weapons VALUES(70,1,'281',2,3,'3',6,2,'0.1','1',60,'1','Hand Crossbow','Sometimes referred to as an alley bow by rogues or ruffians, this small crossbow fires small bolts that are sometimes used to deliver poison to the target. It''s small enough to be shot one-handed, but it still requires two hands to load.');
INSERT INTO weapons VALUES(71,1,'281',2,3,'4',10,2,'2','2',120,'2','Heavy Crossbow','This large crossbow is harder to load and more substantial than a regular crossbow, but it packs a greater punch.');
INSERT INTO weapons VALUES(72,1,'282',2,6,'0.1',6,2,'0.1','1',30,'','Javelin','This thin spear is well balanced for throwing but is not designed for melee use.');
INSERT INTO weapons VALUES(73,1,'282',2,13,'0',6,1,'0.1','1',50,'1','Sling','Little more than a leather cup attached to a pair of straps, a sling can be used to fling smooth stones or sling bullets at a range.');
INSERT INTO weapons VALUES(74,1,'282',3,2,'','',NULL,'0.1','1',20,'','Alchemical Bomb','These bombs come in a variety of types and levels of power, but no matter the variety, you throw the bomb at the target and it explodes, unleashing its alchemical blast.');
INSERT INTO weapons VALUES(75,1,'282',3,3,'20',8,2,'2','1+',100,'0','Composite Longbow','This projectile weapon is made from horn, wood, and sinew laminated together to increase the power of its pull and the force of its projectile. Like all longbows, its great size also increases the bow''s range and power. You must use two hands to fire it, and it cannot be used while mounted. Any time an ability is specifically restricted to a longbow, such as Erastil''s favored weapon, it also applies to composite longbows unless otherwise stated.');
INSERT INTO weapons VALUES(76,1,'282',3,3,'14',6,2,'1','1+',60,'0','Composite Shortbow','This shortbow is made from horn, wood, and sinew laminated together to increase the power of its pull and the force of its projectile. Its compact size and power make it a favorite of mounted archers. Any time an ability is specifically restricted to a shortbow, it also applies to composite shortbows unless otherwise stated.');
INSERT INTO weapons VALUES(77,1,'282',3,13,'5',10,1,'1','2',80,'1','Halfling Sling Staff','This staff ends in a Y-shaped split that cradles a sling. The length of the staff provides excellent leverage when used two‑handed to fling rocks or bullets from the sling.');
INSERT INTO weapons VALUES(78,1,'282',3,3,'6',8,2,'2','1+',100,'0','Longbow','This 5-foot-tall bow, usually made of a single piece of elm, hickory, or yew, has a powerful draw and is excellent at propelling arrows with great force and at an extreme distance. You must use two hands to fire a longbow, and it can''t be used while mounted.');
INSERT INTO weapons VALUES(79,1,'282',3,3,'3',6,2,'1','1+',60,'0','Shortbow','This smaller bow is made of a single piece of wood and favored by skirmishers and cavalry.');
INSERT INTO weapons VALUES(80,1,'282',3,6,'0.01',4,2,'','1',20,'0','Shuriken','This throwing star is a small piece of flat metal with sharp edges, designed to be flung with a flick of the wrist.');
COMMIT;

BEGIN TRANSACTION;
INSERT INTO weapons_traits VALUES(1,0,217);
INSERT INTO weapons_traits VALUES(2,0,226);
INSERT INTO weapons_traits VALUES(3,0,235);
INSERT INTO weapons_traits VALUES(4,0,249);
INSERT INTO weapons_traits VALUES(5,1,203);
INSERT INTO weapons_traits VALUES(6,1,217);
INSERT INTO weapons_traits VALUES(7,1,223);
INSERT INTO weapons_traits VALUES(8,1,237);
INSERT INTO weapons_traits VALUES(9,1,261);
INSERT INTO weapons_traits VALUES(10,2,245);
INSERT INTO weapons_traits VALUES(11,3,217);
INSERT INTO weapons_traits VALUES(12,3,226);
INSERT INTO weapons_traits VALUES(13,3,245);
INSERT INTO weapons_traits VALUES(14,3,250);
INSERT INTO weapons_traits VALUES(15,3,259);
INSERT INTO weapons_traits VALUES(16,4,217);
INSERT INTO weapons_traits VALUES(17,4,228);
INSERT INTO weapons_traits VALUES(18,5,98);
INSERT INTO weapons_traits VALUES(19,5,203);
INSERT INTO weapons_traits VALUES(20,5,217);
INSERT INTO weapons_traits VALUES(21,5,221);
INSERT INTO weapons_traits VALUES(22,5,234);
INSERT INTO weapons_traits VALUES(23,6,217);
INSERT INTO weapons_traits VALUES(24,6,226);
INSERT INTO weapons_traits VALUES(25,6,242);
INSERT INTO weapons_traits VALUES(26,7,241);
INSERT INTO weapons_traits VALUES(27,8,242);
INSERT INTO weapons_traits VALUES(28,9,250);
INSERT INTO weapons_traits VALUES(29,9,260);
INSERT INTO weapons_traits VALUES(30,10,217);
INSERT INTO weapons_traits VALUES(31,10,226);
INSERT INTO weapons_traits VALUES(32,10,246);
INSERT INTO weapons_traits VALUES(33,11,245);
INSERT INTO weapons_traits VALUES(34,12,217);
INSERT INTO weapons_traits VALUES(35,12,228);
INSERT INTO weapons_traits VALUES(36,13,248);
INSERT INTO weapons_traits VALUES(37,13,262);
INSERT INTO weapons_traits VALUES(38,14,248);
INSERT INTO weapons_traits VALUES(39,14,264);
INSERT INTO weapons_traits VALUES(40,15,243);
INSERT INTO weapons_traits VALUES(41,16,234);
INSERT INTO weapons_traits VALUES(42,16,237);
INSERT INTO weapons_traits VALUES(43,16,241);
INSERT INTO weapons_traits VALUES(44,16,246);
INSERT INTO weapons_traits VALUES(45,17,203);
INSERT INTO weapons_traits VALUES(46,17,217);
INSERT INTO weapons_traits VALUES(47,17,219);
INSERT INTO weapons_traits VALUES(48,17,226);
INSERT INTO weapons_traits VALUES(49,17,230);
INSERT INTO weapons_traits VALUES(50,18,224);
INSERT INTO weapons_traits VALUES(51,18,226);
INSERT INTO weapons_traits VALUES(52,18,227);
INSERT INTO weapons_traits VALUES(53,19,227);
INSERT INTO weapons_traits VALUES(54,19,243);
INSERT INTO weapons_traits VALUES(55,20,203);
INSERT INTO weapons_traits VALUES(56,20,217);
INSERT INTO weapons_traits VALUES(57,20,219);
INSERT INTO weapons_traits VALUES(58,20,221);
INSERT INTO weapons_traits VALUES(59,20,226);
INSERT INTO weapons_traits VALUES(60,20,232);
INSERT INTO weapons_traits VALUES(61,20,245);
INSERT INTO weapons_traits VALUES(62,21,222);
INSERT INTO weapons_traits VALUES(63,21,243);
INSERT INTO weapons_traits VALUES(64,21,246);
INSERT INTO weapons_traits VALUES(65,22,221);
INSERT INTO weapons_traits VALUES(66,22,227);
INSERT INTO weapons_traits VALUES(67,22,241);
INSERT INTO weapons_traits VALUES(68,22,257);
INSERT INTO weapons_traits VALUES(69,23,203);
INSERT INTO weapons_traits VALUES(70,23,229);
INSERT INTO weapons_traits VALUES(71,23,246);
INSERT INTO weapons_traits VALUES(72,23,248);
INSERT INTO weapons_traits VALUES(73,23,250);
INSERT INTO weapons_traits VALUES(74,23,260);
INSERT INTO weapons_traits VALUES(75,23,263);
INSERT INTO weapons_traits VALUES(76,24,243);
INSERT INTO weapons_traits VALUES(77,25,220);
INSERT INTO weapons_traits VALUES(78,25,242);
INSERT INTO weapons_traits VALUES(79,26,225);
INSERT INTO weapons_traits VALUES(80,26,267);
INSERT INTO weapons_traits VALUES(81,27,250);
INSERT INTO weapons_traits VALUES(82,27,260);
INSERT INTO weapons_traits VALUES(83,28,241);
INSERT INTO weapons_traits VALUES(84,28,246);
INSERT INTO weapons_traits VALUES(85,29,241);
INSERT INTO weapons_traits VALUES(86,29,250);
INSERT INTO weapons_traits VALUES(87,29,259);
INSERT INTO weapons_traits VALUES(88,30,217);
INSERT INTO weapons_traits VALUES(89,30,243);
INSERT INTO weapons_traits VALUES(90,30,245);
INSERT INTO weapons_traits VALUES(91,31,203);
INSERT INTO weapons_traits VALUES(92,31,230);
INSERT INTO weapons_traits VALUES(93,31,241);
INSERT INTO weapons_traits VALUES(94,31,246);
INSERT INTO weapons_traits VALUES(95,31,250);
INSERT INTO weapons_traits VALUES(96,31,260);
INSERT INTO weapons_traits VALUES(97,32,203);
INSERT INTO weapons_traits VALUES(98,32,217);
INSERT INTO weapons_traits VALUES(99,32,234);
INSERT INTO weapons_traits VALUES(100,32,246);
INSERT INTO weapons_traits VALUES(101,33,203);
INSERT INTO weapons_traits VALUES(102,33,221);
INSERT INTO weapons_traits VALUES(103,33,248);
INSERT INTO weapons_traits VALUES(104,33,250);
INSERT INTO weapons_traits VALUES(105,33,257);
INSERT INTO weapons_traits VALUES(106,33,260);
INSERT INTO weapons_traits VALUES(107,33,263);
INSERT INTO weapons_traits VALUES(108,34,203);
INSERT INTO weapons_traits VALUES(109,34,217);
INSERT INTO weapons_traits VALUES(110,34,226);
INSERT INTO weapons_traits VALUES(111,34,246);
INSERT INTO weapons_traits VALUES(112,35,221);
INSERT INTO weapons_traits VALUES(113,35,233);
INSERT INTO weapons_traits VALUES(114,35,241);
INSERT INTO weapons_traits VALUES(115,35,257);
INSERT INTO weapons_traits VALUES(116,35,268);
INSERT INTO weapons_traits VALUES(117,36,217);
INSERT INTO weapons_traits VALUES(118,36,245);
INSERT INTO weapons_traits VALUES(119,37,217);
INSERT INTO weapons_traits VALUES(120,37,225);
INSERT INTO weapons_traits VALUES(121,37,265);
INSERT INTO weapons_traits VALUES(122,38,250);
INSERT INTO weapons_traits VALUES(123,38,260);
INSERT INTO weapons_traits VALUES(124,39,217);
INSERT INTO weapons_traits VALUES(125,39,222);
INSERT INTO weapons_traits VALUES(126,39,226);
INSERT INTO weapons_traits VALUES(127,39,237);
INSERT INTO weapons_traits VALUES(128,39,250);
INSERT INTO weapons_traits VALUES(129,39,259);
INSERT INTO weapons_traits VALUES(130,40,242);
INSERT INTO weapons_traits VALUES(131,41,203);
INSERT INTO weapons_traits VALUES(132,41,220);
INSERT INTO weapons_traits VALUES(133,41,222);
INSERT INTO weapons_traits VALUES(134,41,226);
INSERT INTO weapons_traits VALUES(135,41,234);
INSERT INTO weapons_traits VALUES(136,42,203);
INSERT INTO weapons_traits VALUES(137,42,217);
INSERT INTO weapons_traits VALUES(138,42,222);
INSERT INTO weapons_traits VALUES(139,42,236);
INSERT INTO weapons_traits VALUES(140,43,225);
INSERT INTO weapons_traits VALUES(141,43,266);
INSERT INTO weapons_traits VALUES(142,44,222);
INSERT INTO weapons_traits VALUES(143,44,241);
INSERT INTO weapons_traits VALUES(144,45,221);
INSERT INTO weapons_traits VALUES(145,45,222);
INSERT INTO weapons_traits VALUES(146,45,226);
INSERT INTO weapons_traits VALUES(147,45,257);
INSERT INTO weapons_traits VALUES(148,46,203);
INSERT INTO weapons_traits VALUES(149,46,217);
INSERT INTO weapons_traits VALUES(150,46,222);
INSERT INTO weapons_traits VALUES(151,46,226);
INSERT INTO weapons_traits VALUES(152,46,234);
INSERT INTO weapons_traits VALUES(153,46,250);
INSERT INTO weapons_traits VALUES(154,46,261);
INSERT INTO weapons_traits VALUES(155,47,217);
INSERT INTO weapons_traits VALUES(156,47,235);
INSERT INTO weapons_traits VALUES(157,48,227);
INSERT INTO weapons_traits VALUES(158,48,243);
INSERT INTO weapons_traits VALUES(159,49,221);
INSERT INTO weapons_traits VALUES(160,49,246);
INSERT INTO weapons_traits VALUES(161,49,258);
INSERT INTO weapons_traits VALUES(162,53,217);
INSERT INTO weapons_traits VALUES(163,53,226);
INSERT INTO weapons_traits VALUES(164,53,250);
INSERT INTO weapons_traits VALUES(165,53,259);
INSERT INTO weapons_traits VALUES(166,54,203);
INSERT INTO weapons_traits VALUES(167,54,222);
INSERT INTO weapons_traits VALUES(168,54,226);
INSERT INTO weapons_traits VALUES(169,54,246);
INSERT INTO weapons_traits VALUES(170,55,217);
INSERT INTO weapons_traits VALUES(171,55,221);
INSERT INTO weapons_traits VALUES(172,55,226);
INSERT INTO weapons_traits VALUES(173,55,245);
INSERT INTO weapons_traits VALUES(174,55,250);
INSERT INTO weapons_traits VALUES(175,55,259);
INSERT INTO weapons_traits VALUES(176,56,203);
INSERT INTO weapons_traits VALUES(177,56,234);
INSERT INTO weapons_traits VALUES(178,56,246);
INSERT INTO weapons_traits VALUES(179,57,245);
INSERT INTO weapons_traits VALUES(180,58,222);
INSERT INTO weapons_traits VALUES(181,58,243);
INSERT INTO weapons_traits VALUES(182,58,246);
INSERT INTO weapons_traits VALUES(183,59,242);
INSERT INTO weapons_traits VALUES(184,60,222);
INSERT INTO weapons_traits VALUES(185,60,226);
INSERT INTO weapons_traits VALUES(186,60,235);
INSERT INTO weapons_traits VALUES(187,60,241);
INSERT INTO weapons_traits VALUES(188,60,246);
INSERT INTO weapons_traits VALUES(189,61,203);
INSERT INTO weapons_traits VALUES(190,61,240);
INSERT INTO weapons_traits VALUES(191,61,244);
INSERT INTO weapons_traits VALUES(192,61,245);
INSERT INTO weapons_traits VALUES(193,61,246);
INSERT INTO weapons_traits VALUES(194,62,223);
INSERT INTO weapons_traits VALUES(195,62,243);
INSERT INTO weapons_traits VALUES(196,62,248);
INSERT INTO weapons_traits VALUES(197,62,264);
INSERT INTO weapons_traits VALUES(198,63,203);
INSERT INTO weapons_traits VALUES(199,63,229);
INSERT INTO weapons_traits VALUES(200,63,241);
INSERT INTO weapons_traits VALUES(201,64,203);
INSERT INTO weapons_traits VALUES(202,64,227);
INSERT INTO weapons_traits VALUES(203,64,236);
INSERT INTO weapons_traits VALUES(204,64,243);
INSERT INTO weapons_traits VALUES(205,65,203);
INSERT INTO weapons_traits VALUES(206,65,217);
INSERT INTO weapons_traits VALUES(207,65,226);
INSERT INTO weapons_traits VALUES(208,65,247);
INSERT INTO weapons_traits VALUES(209,66,203);
INSERT INTO weapons_traits VALUES(210,66,221);
INSERT INTO weapons_traits VALUES(211,66,246);
INSERT INTO weapons_traits VALUES(212,67,217);
INSERT INTO weapons_traits VALUES(213,67,235);
INSERT INTO weapons_traits VALUES(214,69,217);
INSERT INTO weapons_traits VALUES(215,69,245);
INSERT INTO weapons_traits VALUES(216,72,245);
INSERT INTO weapons_traits VALUES(217,73,238);
INSERT INTO weapons_traits VALUES(218,75,221);
INSERT INTO weapons_traits VALUES(219,75,238);
INSERT INTO weapons_traits VALUES(220,75,251);
INSERT INTO weapons_traits VALUES(221,75,258);
INSERT INTO weapons_traits VALUES(222,75,269);
INSERT INTO weapons_traits VALUES(223,76,221);
INSERT INTO weapons_traits VALUES(224,76,238);
INSERT INTO weapons_traits VALUES(225,76,258);
INSERT INTO weapons_traits VALUES(226,77,203);
INSERT INTO weapons_traits VALUES(227,77,232);
INSERT INTO weapons_traits VALUES(228,77,238);
INSERT INTO weapons_traits VALUES(229,78,221);
INSERT INTO weapons_traits VALUES(230,78,251);
INSERT INTO weapons_traits VALUES(231,78,258);
INSERT INTO weapons_traits VALUES(232,78,269);
INSERT INTO weapons_traits VALUES(233,79,221);
INSERT INTO weapons_traits VALUES(234,79,258);
INSERT INTO weapons_traits VALUES(235,80,203);
INSERT INTO weapons_traits VALUES(236,80,217);
INSERT INTO weapons_traits VALUES(237,80,234);
INSERT INTO weapons_traits VALUES(238,80,245);
COMMIT;
